### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by copy-and-paste** [incredibleindishell/SSRF_Vulnerable_Lab#4]
Can you please make a docker file?

**Comment by JonCooperWorks** [comment]
I've created a Dockerfile on my fork https://github.com/JonCooperWorks/SSRF_Vulnerable_Lab. I'm making a PR with this Dockerfile to this repo.

**Comment by incredibleindishell** [comment]
Thank you Jon cooper for your time and efforts :)

**Comment by nine9-nine9** [comment]
Thanks @incredibleindishell and @JonCooperWorks
