### ISSUE TITLE
Setting up the DNS

### ISSUE THREAD

**Issue by 007divyachawla** [incredibleindishell/SSRF_Vulnerable_Lab#7]
Hello @incredibleindishell can you please provide any guidance in setting up the own DNS and perform the DNS rebinding attack, any article or any tutorial is fine.

**Comment by incredibleindishell** [comment]
Hello sir,

Currently, I am using Namecheap DNS to perform DNS Rebinding attack. In Namecheap domain management panel, I am adding multiple 'A Record' entries (Pointing to internal IPs). The only thing which is required is, keeping the TTL as minimal as you can (1 minute in this case).
Attaching screenshot for the reference. 

For manual configuration, I will provide the information. 

![Advanced DNS](https://user-images.githubusercontent.com/10351062/143222625-10ab8482-046a-44da-a4ed-c8d0140dbb26.png)
